name: music_player
description: "Material You Music Player - Local music player with Coriander Player design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
    # Audio related
  audioplayers: ^5.2.1
  file_picker: ^10.1.9
  path_provider: ^2.1.1  # Metadata reading
  audio_metadata_reader: 1.4.1
  flutter_taggy: ^0.1.2+3 # Added for reading embedded lyrics
  uuid: ^3.0.7 # Added uuid package

  # State management
  provider: ^6.1.1

  # UI & Design
  dynamic_color: ^1.6.8
  palette_generator: ^0.3.3+3    # Storage & File handling
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  permission_handler: ^11.1.0
  fullscreen_window: ^1.1.0
  path: ^1.8.3
  window_manager: ^0.5.0
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/asset/fonts/
    - lib/asset/icon/
  fonts:
    - family: MiSans-Bold
      fonts:
        - asset: lib/asset/fonts/MiSans-Bold.ttf
          weight: 700